## BeOS Generic Makefile v2.2 ##
NAME= ../FreeWheely
TYPE= SHARED
SRCS= FreeWheely.cpp
LIBS= _APP_ be root
OPTIMIZE= FULL
DEFINES= 
WARNINGS = 
SYMBOLS = 
DEBUGGER = 
COMPILER_FLAGS =
LINKER_FLAGS =

## include the makefile-engine
include $(BUILDHOME)/etc/makefile-engine
