## BeOS Generic Makefile v2.2 ##
NAME= ../WheelTest
TYPE= APP
SRCS= WheelTest.cpp
LIBS= be stdc++
OPTIMIZE= FULL
DEFINES= 
WARNINGS = 
SYMBOLS = 
DEBUGGER = 
COMPILER_FLAGS =
LINKER_FLAGS =

## include the makefile-engine
include $(BUILDHOME)/etc/makefile-engine
